/**
 * Hardhat Configuration Generator
 * Generates Hardhat 3 config files, sample sources and .env templates for
 * Hedera networks. Everything is ESM, as Hardhat 3 requires.
 */

/**
 * Network configuration
 */
export interface NetworkConfig {
  name: string;
  rpcUrl: string;
  chainId: number;
  accounts?: string[];
}

/**
 * Hedera network configurations
 */
export const HEDERA_NETWORKS = {
  mainnet: {
    name: 'mainnet',
    rpcUrl: 'https://mainnet.hashio.io/api',
    chainId: 295,
  },
  testnet: {
    name: 'testnet',
    rpcUrl: 'https://testnet.hashio.io/api',
    chainId: 296,
  },
  previewnet: {
    name: 'previewnet',
    rpcUrl: 'https://previewnet.hashio.io/api',
    chainId: 297,
  },
  local: {
    name: 'local',
    rpcUrl: 'http://localhost:7546',
    chainId: 298,
  },
};

export type HederaNetworkName = keyof typeof HEDERA_NETWORKS;

/**
 * Versions installed by `hardhat_project init` (checked against npm on 2026-09-09)
 */
export const HARDHAT_SCAFFOLD_PACKAGES = {
  hardhat: 'hardhat@^3.16.0',
  toolbox: '@nomicfoundation/hardhat-toolbox-mocha-ethers@^3.0.7',
  dotenv: 'dotenv@^17.4.2',
  typescript: [
    'typescript@^5.8.0',
    '@types/node@^22.0.0',
    '@types/mocha@^10.0.10',
    '@types/chai@^5.2.0',
  ],
};

/**
 * Hardhat 3 `networks` entry for a Hedera network (JSON-RPC relay, ECDSA key
 * from `<NETWORK>_PRIVATE_KEY`). Used by the config generator and by
 * `hardhat_project config_network`.
 */
export function generateNetworkEntry(options: {
  name: string;
  rpcUrl: string;
  chainId: number;
  indent?: string;
}): string {
  const indent = options.indent ?? '    ';
  const envPrefix = options.name.toUpperCase().replace(/[^A-Z0-9]/g, '_');
  return `${indent}${options.name}: {
${indent}  type: "http",
${indent}  chainType: "generic",
${indent}  url: process.env.${envPrefix}_RPC_URL || "${options.rpcUrl}",
${indent}  accounts: process.env.${envPrefix}_PRIVATE_KEY ? [process.env.${envPrefix}_PRIVATE_KEY] : [],
${indent}  chainId: ${options.chainId},
${indent}}`;
}

/**
 * Generate hardhat.config.{js,ts} for Hedera (Hardhat 3, ESM).
 *
 * The toolbox is registered in `plugins` (Hardhat 3 ignores bare imports),
 * networks are `type: "http"` with `chainType: "generic"`, and verification
 * targets Sourcify, which is what HashScan reads.
 */
export function generateHederaHardhatConfig(options: {
  solidity?: string;
  networks?: HederaNetworkName[];
  typescript?: boolean;
}): string {
  const solidity = options.solidity || '0.8.20';
  const networks = options.networks || ['testnet', 'local'];
  const typescript = options.typescript || false;

  const networkConfigs = networks
    .map((net) => {
      const network = HEDERA_NETWORKS[net];
      return generateNetworkEntry({ name: net, rpcUrl: network.rpcUrl, chainId: network.chainId });
    })
    .join(',\n');

  const typeComment = typescript
    ? ''
    : `/** @type {import("hardhat/config").HardhatUserConfig} */
`;

  return `import hardhatToolboxMochaEthers from "@nomicfoundation/hardhat-toolbox-mocha-ethers";
import { defineConfig } from "hardhat/config";
import "dotenv/config";

// Generated by HashPilot for Hedera. Hardhat 3: plugins must be listed in \`plugins\`.
// Operator credentials are injected as <NETWORK>_PRIVATE_KEY / <NETWORK>_RPC_URL
// when commands run through HashPilot; otherwise put them in .env.
${typeComment}export default defineConfig({
  plugins: [hardhatToolboxMochaEthers],
  solidity: {
    version: "${solidity}",
    settings: {
      optimizer: {
        enabled: true,
        runs: 500,
      },
    },
  },
  networks: {
${networkConfigs},
  },
  verify: {
    // HashScan reads verification status from Sourcify (chains 295 and 296)
    sourcify: { enabled: true },
    etherscan: { enabled: false },
    blockscout: { enabled: false },
  },
});
`;
}

/**
 * Generate .env file template for Hedera
 */
export function generateEnvTemplate(networks?: HederaNetworkName[]): string {
  const nets = networks || ['testnet', 'local'];

  const envVars = nets
    .map((net) => {
      const network = HEDERA_NETWORKS[net];
      const envPrefix = net.toUpperCase();

      return `# ${network.name.charAt(0).toUpperCase() + network.name.slice(1)} Network (chain ID ${network.chainId})
${envPrefix}_RPC_URL=${network.rpcUrl}
${envPrefix}_PRIVATE_KEY=0x[your-hex-encoded-ECDSA-private-key]
`;
    })
    .join('\n');

  return `# Hedera Network Configuration
# DO NOT commit this file to version control
# Copy this to .env and fill in your private keys (ECDSA, raw hex with 0x prefix).
# When running through HashPilot, the MCP operator account is injected automatically
# and these values are only used as fallbacks.

${envVars}
# Optional: Gas reporter
REPORT_GAS=false
`;
}

/**
 * Generate sample Greeter contract
 */
export function generateSampleContract(): string {
  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title Greeter
 * @dev Simple contract that stores and returns a greeting message
 */
contract Greeter {
    string private greeting;

    event GreetingChanged(string oldGreeting, string newGreeting);

    constructor(string memory _greeting) {
        greeting = _greeting;
    }

    function greet() public view returns (string memory) {
        return greeting;
    }

    function setGreeting(string memory _greeting) public {
        string memory oldGreeting = greeting;
        greeting = _greeting;
        emit GreetingChanged(oldGreeting, _greeting);
    }
}
`;
}

/**
 * Generate sample deployment script (Hardhat 3: `network.create()` returns
 * the connection that carries `ethers`; `--network` selects the target).
 */
export function generateSampleDeployScript(_typescript?: boolean): string {
  return `import { network } from "hardhat";

// Run with: npx hardhat run scripts/deploy.js --network testnet
const { ethers } = await network.create();

const [deployer] = await ethers.getSigners();
if (!deployer) {
  throw new Error("No account configured for this network. Set <NETWORK>_PRIVATE_KEY in .env");
}

console.log("Deploying contracts with account:", deployer.address);
console.log("Account balance:", ethers.formatEther(await ethers.provider.getBalance(deployer.address)), "HBAR");

const greeter = await ethers.deployContract("Greeter", ["Hello, Hedera!"]);
await greeter.waitForDeployment();

console.log("Greeter deployed to:", await greeter.getAddress());
`;
}

/**
 * Generate sample test file (Hardhat 3 + mocha + ethers)
 */
export function generateSampleTest(_typescript?: boolean): string {
  return `import { expect } from "chai";
import { network } from "hardhat";

const { ethers } = await network.create();

describe("Greeter", function () {
  it("Should return the greeting", async function () {
    const greeter = await ethers.deployContract("Greeter", ["Hello, Hedera!"]);

    expect(await greeter.greet()).to.equal("Hello, Hedera!");
  });

  it("Should update the greeting", async function () {
    const greeter = await ethers.deployContract("Greeter", ["Hello, Hedera!"]);

    await greeter.setGreeting("Hola, Hedera!");
    expect(await greeter.greet()).to.equal("Hola, Hedera!");
  });

  it("Should emit GreetingChanged event", async function () {
    const greeter = await ethers.deployContract("Greeter", ["Hello, Hedera!"]);

    await expect(greeter.setGreeting("Hola, Hedera!"))
      .to.emit(greeter, "GreetingChanged")
      .withArgs("Hello, Hedera!", "Hola, Hedera!");
  });
});
`;
}

/**
 * Generate sample Ignition module
 */
export function generateSampleIgnitionModule(): string {
  return `import { buildModule } from "@nomicfoundation/hardhat-ignition/modules";

// Deploy with: npx hardhat ignition deploy ignition/modules/Greeter.js --network testnet
export default buildModule("GreeterModule", (m) => {
  const greeting = m.getParameter("greeting", "Hello, Hedera!");
  const greeter = m.contract("Greeter", [greeting]);

  return { greeter };
});
`;
}

/**
 * Generate tsconfig.json for TypeScript projects (matches the Hardhat 3 template)
 */
export function generateTsConfig(): string {
  return `{
  "compilerOptions": {
    "lib": ["es2023"],
    "module": "node20",
    "target": "es2023",
    "skipLibCheck": true,
    "outDir": "dist",
    "types": ["node", "mocha"],
    "verbatimModuleSyntax": true
  }
}
`;
}

/**
 * Generate .gitignore for Hardhat project
 */
export function generateGitignore(): string {
  return `# Node modules
/node_modules

# Compilation output
/dist

# Hardhat build artifacts
/artifacts
/cache

# Typechain output
/types
typechain-types

# Ignition deployments to the in-memory network
/ignition/deployments/chain-31337

# Environment files
.env
.env.*
!.env.example

# Coverage
/coverage
coverage.json

# MacOS
.DS_Store

# IDE
.vscode
.idea
*.swp
*.swo

# Logs
*.log
`;
}

/**
 * Generate README for Hardhat project
 */
export function generateReadme(): string {
  return `# Hedera Hardhat Project

A Hardhat 3 project configured for Hedera. It comes with a sample contract, a mocha test, a deployment script and an Ignition module.

## Setup

Install dependencies:

\`\`\`bash
npm install
\`\`\`

Copy \`.env.example\` to \`.env\` and fill in your ECDSA private keys (when you run commands through HashPilot, the MCP operator account is injected automatically):

\`\`\`bash
cp .env.example .env
\`\`\`

## Available Commands

\`\`\`bash
# Compile contracts
npx hardhat compile

# Run tests (in-memory Hardhat network)
npx hardhat test

# Deploy to testnet with the script
npx hardhat run scripts/deploy.js --network testnet

# Deploy to testnet with Ignition
npx hardhat ignition deploy ignition/modules/Greeter.js --network testnet

# Verify on Sourcify (what HashScan reads)
npx hardhat verify --network testnet <address> "Hello, Hedera!"

# Clean artifacts
npx hardhat clean
\`\`\`

## Networks

- **Mainnet**: Chain ID 295
- **Testnet**: Chain ID 296
- **Previewnet**: Chain ID 297
- **Local**: Chain ID 298 (Hedera local node)

## Learn More

- [Hardhat Documentation](https://hardhat.org/docs)
- [Hedera Documentation](https://docs.hedera.com/)
- [Hedera Smart Contract Guide](https://docs.hedera.com/hedera/core-concepts/smart-contracts)
`;
}
